### ISSUE TITLE
Datenschutzerklärung / Data Protection Statement

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#165]
**As an app user, I want to be able to read the data protection statment in order to know what happens with my data and whom I can contact.**

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2487-12430&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

**Comment by Sommergiulia** [comment]
https://www.gruene.de/service/datenschutz but doesn't work for the App. 
@JuliaFreitagBGSt

**Comment by steffenkleinle** [comment]
> https://www.gruene.de/service/datenschutz but doesn't work for the App. @JuliaFreitagBGSt

@Sommergiulia @JuliaFreitagBGSt could you please clarify what `but doesn't work for the App` means? Is this still the correct URL for us to use in the settings/login screen?

**Comment by JuliaFreitagBGSt** [comment]
> > https://www.gruene.de/service/datenschutz but doesn't work for the App. @JuliaFreitagBGSt
> 
> @Sommergiulia @JuliaFreitagBGSt could you please clarify what `but doesn't work for the App` means? Is this still the correct URL for us to use in the settings/login screen?

Yes, the URL ist correct, you can use it. But the content must be updated by us and adapted to an app
