### ISSUE TITLE
Impressum / Legal Notice

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#166]
**As an app user, I want to be able to read the legal notice (_Impressum_) to find out the editorial responsibility for texts and legal responsibility for the app.**

For more information, please consult: https://www.bmuv.de/themen/verbraucherschutz/digitaler-verbraucherschutz/impressumspflicht

Design:

![grafik](https://github.com/user-attachments/assets/24f02f54-d7d8-4078-9fe9-c0222a37cf95)

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2520-3305&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

**Comment by Sommergiulia** [comment]
The Politische Bundesgeschäftsführerin needs to be changed (after BDK). 
Needs to be added: How to contact us easily, this can either be electronical or non electronical. Usually this is an e-Mail address or a phone number.
