### ISSUE TITLE
Campaign | Doors: Display focus areas

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#169]
**As an app user, I want to see the focus areas defined for door-to-door campaigning shown on the map in order to most efficiently canvas these.**

For Release 0* the focus area will be implemented directly in the data base.

Acceptance criteria:
- [x] Focus area layer can be activated / deactivated #268 
- [x] Focus areas colors: #284 
- [x] Layers and individual elements are displayed in the App for reference and are "read only"

Extension:
- #381 

Design:
![grafik](https://github.com/user-attachments/assets/e6286445-d009-4074-9c0e-2e67a33eb9dc)

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2685-14759&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/78

Pollion reference: https://github.com/pollion/sunflower-app/issues/77

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/77

**Comment by nscharioth** [comment]
Review issue description and move to "Ready for Development". @leagerndt @JuliaFreitagBGSt

**Comment by JuliaFreitagBGSt** [comment]
issue is reviewed, rfd
