### ISSUE TITLE
Campaign | Doors: Enter new door(s)

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#171]
**As an app user, I want to record that I campaigned door-to-door at an address or in a larger freely-definable area and how many doors thereof were opened in order to note for myself and other campaigners that the building or area have already been canvassed.**

The process to enter a new visited door in #217 :
- Click on locator icon
- Choose "+Adresse"
- Fill in information in form. The form includes the address as well as the number of opened and unopened doors a the location.

Acceptance criteria:
- [x] Most commonly only 1 door is entered. This should be the standard number selected when entering a new door

<img width="314" alt="361200071-809a8870-40e6-4e18-930a-2589be19fa2a" src="https://github.com/user-attachments/assets/fd0be90a-7d8a-47e2-a622-3cbdb667de1c">
<img width="318" alt="361200073-9e95ca06-fe56-45c1-b8db-9bf681b45186" src="https://github.com/user-attachments/assets/8fb0cc37-0f25-4d27-8a10-e894514c2557">
<img width="308" alt="361200074-78b6c880-c22c-4ebb-bf25-5be003995496" src="https://github.com/user-attachments/assets/b3db05c9-87ac-4137-9b3d-35b10adf8ce5">

Prototype:
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2911-35705&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2726-11761&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/64

Pollion reference: https://github.com/pollion/sunflower-app/issues/24

**Comment by nscharioth** [comment]
Please review issue description and move to "Ready for Development" column. @leagerndt @JuliaFreitagBGSt

**Comment by JuliaFreitagBGSt** [comment]
issue is reviewed
