### ISSUE TITLE
Campaign | Posters: Enter new poster

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#173]
**As an app user, I want to record newly-placed posters on the map in order to know where posters are and in which condition they are in.**

Posters can be entered (an address can be added analog to Doors and, optionally, a name and a photo) by clicking on the central add-POI element. Poster icons are green (active), red (damaged) or gray (marked as taken down).

The process to enter a new poster in #183:
- [x] Click on locator icon
- [x] Fill in information in form. The form includes the address.
- [x] as well as the opportunity to add a picture #198 

Acceptance criteria:
- [x] Users can create new poster entries
- [x] When creating a new poster entry, users are first prompted to take a photo of this. The user has the choice of using their camera or uploading an existing photo from their photo library. The user can also chose not to take a picture of the poster.
- [x] Photos are compressed to a reasonable size and meaningful data format (e.g. JPG) in full HD before being uploaded so that poster locations and poster condition are still recognizable.
- [x] A thumbnail of the photo is also created for use in the popup icon

Design:

<img width="316" alt="361200576-013ebf73-cc8d-42e5-aa9d-2b934a09b47e" src="https://github.com/user-attachments/assets/c210e172-52ed-4309-b67e-fd2a3277adcc">

<img width="315" alt="361200578-865248ea-2dab-4704-83d7-0649f473b352" src="https://github.com/user-attachments/assets/20f6ddcb-aedb-4d0c-9975-905cac17ef2c">

Prototype:
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2911-35532&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2718-7292&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/59

Pollion reference: https://github.com/pollion/sunflower-app/issues/26

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/26

**Comment by nscharioth** [comment]
References the API in https://github.com/verdigado/gruene-api/issues/41 and https://github.com/verdigado/gruene-api/issues/42.

**Comment by nscharioth** [comment]
Please review issue description and move to "Ready for Development" column. @leagerndt @JuliaFreitagBGSt

**Comment by JuliaFreitagBGSt** [comment]
issue is reviewed
