### ISSUE TITLE
CD Pipeline für Google Play Store

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene-app#191]
Continuous Delivery Pipeline für Google Play Store einrichten (Production & Beta releases).

**Comment by svenseeberg** [comment]
Deployment für KC Auth App läuft, für Grüne App noch nicht.

**Comment by melegiul** [comment]
Pipeline für die KC Auth App steht bereit. Der Verdigado Account auf der Play Console ist nur noch nicht abgeschlossen, was die Nutzung im Moment noch blockiert.

![image](https://github.com/verdigado/gruene_app/assets/47010475/1fdda11a-5244-49ed-b96b-8fa18708cc61)

Deshalb ist für den Play-Upload-CircleCI-Job gerade noch eine dry run Option gesetzt. Sobald der Account fertig ist, kann diese Zeile einfach entfernt werden:

https://github.com/verdigado/kc_auth_app/blob/ef4929ea3a35fa28069f9e31d90a7b730b363bc7/android/fastlane/Fastfile#L37

Und der Ziel Track kann in selber Datei dann auch geändert werden.

**Comment by JuliaFreitagBGSt** [comment]
@maxpfe @svenseeberg pls clarify what is needed to complete this issue
