### ISSUE TITLE
Campaign: Homepage Flyer

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#218]
**Flyer stands and flyer areas are coordinated on a clear and easy-to-understand map. Locations where flyers have already been distributed are documented here.**

Addresses of campaign/flyer stands are displayed as icons on the map. Using a filter (layer), flyer routes that were created outside of the app in the campaign planning tool (previously: _Wahlatlas_) and serve as orientation (read only) can be displayed and hidden. The intended direction of movement associated with the flyer route is displayed using small arrows that imply the correct route. Recorded stands (addresses) contain common address fields (analog to doors/canvassing and posters). When entering an area in which flyers have been distributed, anker points can be placed on the map with a button to define the boundaries of the corresponding space. The boundary drawing function can be saved using a confirmation button or cancelled via a secondary button. When entering flyer areas, the address field is omitted and instead there is an input field for the amount of flyers distributed as well as a text input field. A click on a flyer area or flyer stand displays the number of flyers distributed in an overlay with the ability to edit this entry. If the overlay is clicked, an editing dialog is shown: in this dialog, the entry can be edited or deleted (analog to doors/canvassing & posters).

Acceptance criteria for Release 0*:
- [x] #266 
- [x] #278 
- [x] #261 
- [x] #262 

Later implementation 
-  #270 

Design:
![grafik](https://github.com/user-attachments/assets/af40ce37-3e21-4a56-bb93-33151ecfb4cf)

Prototype: https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2670-9749&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

API endpoint reference: https://github.com/verdigado/gruene-api/issues/70

Pollion reference: https://github.com/pollion/sunflower-app/issues/29

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/29

**Comment by nscharioth** [comment]
Please review issue description and move to "Ready for Development" column. @leagerndt @JuliaFreitagBGSt

**Comment by JuliaFreitagBGSt** [comment]
Issue is reviewed.

**Comment by iantrieschmann** [comment]
In light of the new election date for the German federal elections, the priority for flyers (if time allows for development in Release 0*) is:

1. **flow for a new single location (address-bound)**, then
2. flow for a flyer area (Bereich) via vector points
