### ISSUE TITLE
Non-Functional Requirements: Usability

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#237]
Die App sollte so gestaltet sein, dass sie auch von Personen, die nicht regelmäßig digitale Technologien nutzen, einfach bedient werden kann. Die Benutzeroberfläche muss intuitiv und leicht verständlich sein, um eine breite Akzeptanz unter allen Parteimitgliedern zu fördern.

**Comment by nscharioth** [comment]
Not a developer task, therefore closed for similar reasons like #243, see comment: https://github.com/verdigado/gruene_app/issues/243#issuecomment-2466516648

If reopened please describe exact acceptance criteria for developers.
