### ISSUE TITLE
Non-Functional Requirements: Efficiency

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#238]
Der Energieverbrauch der App sollte optimiert sein, um die Batterielaufzeit der Geräte nicht unnötig zu belasten. Dies ist besonders wichtig für die Nutzer:innen, die die App unterwegs verwenden.

**Comment by nscharioth** [comment]
Not a developer task, therefore closed for similar reasons like #243, see comment: https://github.com/verdigado/gruene_app/issues/243#issuecomment-2466516648

If reopened please describe exact acceptance criteria for developers.
