### ISSUE TITLE
Quality Requirements: Quality Standards

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#241]
Die Software soll alle gängigen Sicherheitsstandards erfüllen, um Datenschutz und Datensicherheit zu gewährleisten. Dies schließt die sichere Speicherung und Übertragung von Nutzer:innendaten sowie den Schutz vor unbefugtem Zugriff und Datenlecks ein.

Alle Texte sollten mit Screenreadern kompatibel sein, damit diese vorgelesen werden können.

Die App wird nutzer:innenfreundlich gestaltet, um eine hohe Akzeptanz zu sichern.

**Comment by nscharioth** [comment]
Not a developer task, therefore closed for similar reasons like #243, see comment: https://github.com/verdigado/gruene_app/issues/243#issuecomment-2466516648

If reopened please describe exact acceptance criteria for developers.
