### ISSUE TITLE
Legal Requirements

### ISSUE THREAD

**Issue by iantrieschmann** [verdigado/gruene-app#243]
Bei der Entwicklung und beim Betrieb der App werden die europäischen und deutschen Datenschutzbestimmungen eingehalten. Dies umfasst die Einhaltung der Datenschutz-Grundverordnung (DSGVO), welche strenge Anforderungen an die Verarbeitung personenbezogener Daten stellt. Die App wird so gestaltet, dass sie die Privatsphäre der Nutzer:innen schützt und gleichzeitig die Compliance mit diesen Vorschriften gewährleistet.

**Comment by JuliaFreitagBGSt** [comment]
since this is not a task for developers, but an organizational arrangement/commitment, we could recommend to close this issue as not planned
@maxpfe @nscharioth what do you think?

**Comment by nscharioth** [comment]
> since this is not a task for developers, but an organizational arrangement/commitment, we could recommend to close this issue as not planned
> @maxpfe @nscharioth what do you think?

Yes, exactly, completely agree. This will of course be taken into account by developers, but is not really a task for developers. Same for #236 #237 #238 #239 #240 #241 #242. 

I will close all these issues. Reopen if you see differently.
